---
title: "P8105 HW2 nk3037"
author: "Navya Koneripalli"
date: "2023-10-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
```

# Question 1
### Cleaning pols-month.csv
```{r, message = FALSE}
month_df = 
  tibble(
    month_num = 1:12,
    month = month.name
  )

pols_month_data = 
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  left_join(x = _, y = month_df) |> 
  select(year, month, everything(), -day, -prez_dem, -prez_gop)
```

### Cleaning snp.csv
```{r, message=FALSE}
snp_data = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  arrange(year, month) %>% 
  mutate(month = month.name[month])
```

### Cleaning unemployment.csv
```{r, message=FALSE}
unemployment_data =
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  rename(year = Year) %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  )
```

